using dotnetConf2025.Shared.Models;

namespace dotnetConf2025.Shared.Services
{
    public class SpeakerService
    {
        public IEnumerable<SpeakerModel> GetSpeakers()
        {
            var speakers = new List<SpeakerModel> {
                new SpeakerModel {
                    Id = "WillHuang",
                    Name = "Will Huang",
                    JobTitle = "多奇數位創意 技術總監",
                    PictureUrl ="./img/speakers/Will 保哥.jpg",
                    BlogUrl = "http://blog.miniasp.com/",
                    FacebookUrl = "https://www.facebook.com/will.fans/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "現任「多奇數位創意有限公司」技術總監。2024 年榮獲 GenAI 方向的 Google Developer Expert (GDE) 開發專家。2019 獲選微軟技術社群區域總監 (Microsoft Regional Director)。2018 年榮獲 Angular 方向的 Google Developer Expert (GDE) 開發專家。連續 18 度當選微軟最有價值專家(MVP)。熟悉 Generative AI、Angular、JavaScript、.NET、C#、Java、Go、Docker、Kubernetes 相關技術。擅長 DevOps 與組織文化建立、軟體團隊建構與管理。熱愛分享知識。",
                    Topic = "ASP.NET Core 10.0 全新功能探索",
                    TopicOutline = "全新的 .NET 10.0 帶來了持續躍進的效能優化，並推出多項突破性創新功能，為開發者提供更強大且高效的開發工具。本次 ASP.NET Core 10.0 不僅加強了對現代雲端原生應用的全面支援，更整合最新的 C# 14 語言特性，賦予開發者更靈活且簡潔的程式設計體驗。於此版本中，我們將見證全新的 OpenAPI 3.1 標準支援、Minimal API 的進階驗證機制，以及靜態資產與響應串流等多方面的效能強化。<br/><br/>這場演講將引領大家深入探索 ASP.NET Core 10.0 的全新功能，揭示它如何革新開發流程並提升系統效能。準備好迎接技術前沿，與我們一同揭開這激動人心的 ASP.NET Core 新篇章吧！",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "DavidTung",
                    Name = "David Tung",
                    JobTitle = "光岩資訊資深技術顧問",
                    PictureUrl ="./img/speakers/David Tung.jpg",
                    BlogUrl = "http://studyhost.blogspot.tw/",
                    FacebookUrl = "http://www.facebook.com/DotNetWalker/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "David 從 Apple II 時代起即投入資訊 IT 與程式設計領域近 30 年，在資訊業界各領域均多有參與。2002 年起投身資訊書籍寫作以及教育訓練、顧問服務之行列，在台灣與大陸共有十數本著作出版。2006 年至今，連續榮獲 20 次微軟最有價值專家（MVP）、2018 年獲選 LAE（LINE API Expert），2020 年獲選微軟技術社群區域總監，並屢次受邀擔歷屆 MS TechED/ Tech‧Days 與各大社群技術研討會講師。",
                    Topic = "變革 👉 面對變革",
                    TopicOutline = "今年的 DevOpsDays 我分享了一場 '變革'。<br/><br/>因為，Sam Altman 說：『(相較於 2025 年初) 軟體工程在 2025 年底 將會變得非常的不同...』<br/><br/>三年前，在沒有所謂 AI 輔助開發的那個年代，要是有人跟我說 軟體專案開發 或 寫程式 這件事，可以自動化到一鍵完成，我會覺得難以置信。<br/><br/>但如今，這都快要變成是我們每天工作的日常了。<br/><br/>AI 對軟體工程、軟體生命週期管理（SDLC），乃至於 DevOps 所帶來的變革，已經來到了 顛覆性的影響。許多曾奉為圭臬的軟體工程方法論與最佳實踐，都正在這場變革中被徹底重塑。<br/><br/> '變革' 之後，我們要來看如何面對變革。<br/><br/>在這場分享中，我們繼續深入探索 AI輔助軟體開發的最新現況與未來的可能發展，並思考：在這場 AI 驅動的技術革命裡，我們該如何才能站穩腳步。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "EdwardKuo",
                    Name = "Edward Kuo",
                    JobTitle = "Microsoft Regional Director",
                    PictureUrl ="./img/speakers/Edward Kuo.jpg",
                    BlogUrl = "https://profile.edwardkuo.dev/",
                    FacebookUrl = "https://www.facebook.com/EdwardKuo.Teched",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "現任美商科技製造公司資訊處資深經理，兼具 Microsoft Regional Director 與 Microsoft Azure MVP 身分，長期投身技術社群與產業實務。擅長雲端架構設計、工業 4.0、供應鏈系統、AI/ML 與 DevOps 解決方案，善於以多元觀點串聯業界需求與技術落地。熱衷於知識分享，活躍於各大技術研討會、社群論壇及企業訓練，亦為多所大學客座講師。致力推動企業數位轉型，持續促進技術交流與社群成長，協助更多團隊實現創新價值。",
                    Topic = "在企業實施混合人工智慧解決方案",
                    TopicOutline = "隨著AI世代的來臨，企業正面對日益多元且複雜的人工智慧需求。混合人工智慧解決方案，將雲端與地端資源有效整合，不僅提升了企業運作的靈活性，也大幅強化了資料安全。借助Azure AI Foundry和Foundry Local，我們能在雲端享有強大的AI運算能力，同時在需要時於地端確保資料隱私與即時處理，滿足各種場景的需求。Azure AI Foundry為企業提供全面且高效的AI開發平台，協助訓練與部署AI模型；而Foundry Local則能在本地安全環境中運行AI解決方案，切合合規及資安的要求。這種混合架構讓我們能夠打造高效、可控且高度整合的人工智慧生態系",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "AndrewWu",
                    Name = "Andrew Wu",
                    JobTitle = "91APP 首席架構師",
                    PictureUrl ="./img/speakers/Andrew Wu.jpg",
                    BlogUrl = "https://columns.chicken-house.net/",
                    FacebookUrl = "https://www.facebook.com/andrew.blog.0928/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "## 講師介紹：Andrew Wu<br/>現任職於大型軟體開發團隊的架構師，負責核心產品的服務化，與內部產品開發團隊的架構改善等任務。在過去的 25 年工作經驗，主要都專注於 .NET 開發 SaaS , B2B2C 的雲端服務。我專長的領域包括: 軟體工程，物件導向設計，分散式系統架構設計，平行處理，API 設計 及 微服務導向架構設計 (microservices) 等。而近年 AI 快速崛起, 我也投入了相關研究。擅長的主題包含: Agent 架構設計, MCP 的設計開發, Context Engineering 等領域。<br/>我樂於分享技術新知與開發的經驗，常在各大研討會或是在社群活動上分享經驗。同時我也有撰寫部落格文章的習慣，希望能累積我的經驗給需要的夥伴們。我深信知識是越分享越精進的，這也是支持我自 2004 至今連續 20 年不間段分享文章的動力來源。<br/><!--more--><br/>## 個人經歷:<br/>* 現任 [91APP](https://www.91app.com), 首席架構師 Chief Architect<br/>* 榮獲 [Microsoft MVP 微軟最有價值專家](https://mvp.microsoft.com/zh-tw/PublicProfile/5002155?fullName=Andrew%20%20Wu) 獎項,2016 ~ 2025<br/>* 擔任多次 Microsoft Azure Cafe, TechDays, TechEd, DevOpsDays Taiwan, .NET Conf 等大型研討會講者，與相關 Azure PaaS 雲端系列課程與企業內訓講師<br/>## 相關連結：<br/>* 安德魯的部落格 / [Facebook](https://www.facebook.com/andrew.blog.0928)<br/>* 安德魯的部落格 / [Threads](https://www.threads.net/@andrew.blog.0928)<br/>* 安德魯的部落格 / [Blog](http://columns.chicken-house.net)<br/>* [GitHub](https://github.com/andrew0928)<br/>* [LinkedIn](https://www.linkedin.com/in/andrew0928/)",
                    Topic = "Designing for Agents: MCP-First Design Concepts",
                    TopicOutline = "這場次我想談 MCP 的設計概念。面對理解能力強大的 AI Agent，需要給他的是有用的 Tool, 而不是硬梆梆的 API。本場以 Anthropic 的 MCP primitives 為骨架，說明如何掌握意圖 (intention) 與流程 (workflow)，用 .NET + MCP SDK 來打造 MCP server。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "YinSangzhi",
                    Name = "尹相志",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/尹相志-AI.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "DataDecision.ai數據科學家，大數據行業經歷今年第27年，於2002年成立台灣第一家大數據顧問公司asiaMiner，曾經協助台灣大型電信公司（中華電信、遠傳電信、台灣大哥大）、銀行（中國信託、台新、台灣銀行、元大、新光、萬泰...等)、零售業（特力屋、7-11）...等企業導入數據科學相關產業應用。也是臺灣微軟在數據科學領域的特約講師，曾獲選2006~2017年微軟最有價值專家(MVP)，於2015~2016年曾兼任上海華院數據（中國第一家大數據顧問公司）之首席數據科學家，於任內發起中國首次國際人工智能競賽「BOT (Brain of things) Shanghai 2016」，同時也擔任2016年與2017年的賽題設計。現任光寶科技、啟雲科技之企業顧問",
                    Topic = "關於語境工程（context engineering)的奇淫巧技",
                    TopicOutline = "在這session中將會透過案例來展示語境工程的技巧實現以及如何整合為組合技",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "IanChan",
                    Name = "陳葵懋 Ian",
                    JobTitle = "微軟最有價值專家",
                    PictureUrl ="./img/speakers/Ian.jpg",
                    BlogUrl = "https://medium.com/playtech",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "https://www.linkedin.com/in/codeian/",
                    Introduction = "目前任職於一等一科技，同時也是微軟 AI 人工智慧最有價值專家（MVP）與微軟認證講師（MCT）。專注於 .NET、Azure 、容器化、雲/地端生成式AI應用解決方案，曾受邀在 Microsoft TechDay、DevDays、.NET Conf Taiwan 、MWC、MOPCON 等大型技術研討會擔任講師，分享業界實戰心法。近年聚焦生成式 AI 、RAG與 AI Agent 的研究，具有實務上的實踐以及培訓經驗。<br/>出版多本生成式AI共同著作：<br/>• AI Agent 奇幻旅程：MCP 通往異世界金鑰（含最新 OpenAI GPT-5 範例）<br/>• Python原力爆擊：OpenAI / Gemini / AWS / Ollama生成式AI應用新手指南<br/>• LangChain 奇幻旅程：OpenAI x Gemini x 多模態應用開發指南<br/>• 極速 ChatGPT 開發者兵器指南：跨界整合 Prompt Flow 、LangChain 與 Semantic Kernel 框架<br/>• 駕馭 ChatGPT 4: 探索 Azure OpenAI 與 Cognitive Service for Language 開發實踐 （使用 .NET 與 Node.js）",
                    Topic = "震撼！SK：我還沒退場啊！Agent Framework：對不起，我來了",
                    TopicOutline = "剛把 Semantic Kernel 的概念摸熟、AI Agent 跑起來，結果微軟突然說：「抱歉，Agent Framework 上線囉～」<br/>每次技術一更新，開發者的心聲大概就是：「我連 Hello World 都還沒寫完啊！」<br/>這場議程不是要你立刻重寫所有專案，也不是 Agent Framework 的官方業配，而是想帶大家一起看看這波框架交接到底在演哪齣。<br/>同時，我也會搶先示範如何用 Agent Framework 開發 AI Agent，看看跟 SK 有哪些不一樣的地方。<br/>面對這場「框架速食時代」的技術換代，我們就邊學邊吐槽吧（啊…可以嗎 ??）。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "KoKo",
                    Name = "KO KO",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/KO KO.jpg",
                    BlogUrl = "",
                    FacebookUrl = "https://www.facebook.com/magic.panda.engineer/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "Ko Ko 連續當選六年微軟 AI （Microsoft AI MVP），曾任職於財星 500 強、美國矽谷科技新創、澳洲雪梨科技新創、美國上市公司等企業，擅長於 AI 技術與軟體開發。他也是大型技術年會的知名講者，包含了. NET Conference、PyCon APAC、PyCon HK、DevDays Asia 等等的國際大型年會，累計已超過萬名聽眾。經營粉專「大魔術熊貓工程師」。目前已經出版五本生成式 AI 應用的書籍。",
                    Topic = "使用 Azure AI 與 LangGraph 來開發 AI Agent",
                    TopicOutline = "<br/>LangChain 是全球最受歡迎 LLM 應用開源框架，其強大的能力和完整的生態系相當受到開發者的歡迎。本演講將帶領您探索如何運用 LangChain 生態系裡專門做 AI Agent 的 LangGraph，結合 Azure AI 的強大功能，進而打造出多功能的 AI Agent。內容將包含 Azure AI 的觀念說明，並且實際 demo 如何整合到 LangChain 的生態系中。<br/>",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "JiaSin",
                    Name = "陳佳新（奇步老爹）",
                    JobTitle = "奇步應用有限公司 執行長",
                    PictureUrl ="./img/speakers/陳佳新.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "彰化軟體公司奇步應用（ChiBuApp Inc.）執行長，微軟AI MVP人工智慧最有價值技術專家，經常在COSCUP、MOPCON、.NET Conf等開發者年會擔任講者，致力於提升故鄉彰化的數位化能力，立志成為地方創生和永續發展最強而有力的數位轉型支持系統。",
                    Topic = "探索Azure AI內容安全，打造負責任的AI",
                    TopicOutline = "大家都有領略過生成式AI的便利，但是AI幻覺可能導致誤導，因此我們將探討如何識別並修正幻覺。以及建立自訂的AI篩選，有效防堵提示注入攻擊，進而提升AI服務的準確性和可靠性。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "GelisWu",
                    Name = "Gelis 吳俊毅",
                    JobTitle = "資深 .NET 技術顧問 & Microsoft MVP 連續七屆",
                    PictureUrl ="./img/speakers/Gelis Wu.jpg",
                    BlogUrl = "http://gelis-dotnet.blogspot.com/",
                    FacebookUrl = "https://www.facebook.com/groups/361804473860062/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "#個人簡介<br/>對寫程式以及軟體開發與架構設計有極大熱誠的阿宅，對物件導向分析與設計領域有些研究，執著在商用的軟體開發與特定方法論的實踐可以發揮最大效益、節省最多成本。現職為.NET技術顧問，因為擔任顧問，因此經歷比較廣，包括軟體架構設計規劃、客製化框架開發、分散式系統設計、Redis Cache 快取導入與快取策略規劃等。<br/><br/>## 顧問資歷：<br/>● 產險公司 - Redis Cache 導入與執行顧問、系統架構顧問<br/>● 新竹科學園區 - .NET 6 系統升級顧問、企業框架設計顧問<br/>● 高雄一卡通 - Unit Test 單元測試導入顧問<br/>● 資策會 - IBM 授權教育訓練中心 - UML 課程講師<br/><br/>## 關於我：<br/>部落格 (Gelis 技術隨筆)：<br/>http://gelis-dotnet.blogspot.tw<br/>https://www.dotblogs.com.tw/gelis/<br/><br/>FB 社團 (軟體開發之路)：<br/>https://www.facebook.com/groups/361804473860062/<br/><br/>FB 粉絲團 (Gelis 的程式設計訓練營)：<br/>https://www.facebook.com/gelis.dev.learning/<br/><br/>我講授過的課程 SlideShare：<br/>https://www.slideshare.net/GelisWu<br/><br/>Github：<br/>https://github.com/wugelis",
                    Topic = "當 Mermaid 遇上 Visual Studio 2026 會迸出什麼火花呢？",
                    TopicOutline = "這是微軟首次將 Mermaid 整合到 Visual Studio。 我們知道在以前 Diagram 的繪製對系統設計分析有莫大的助益，即便到了 AI 的時代，也還是如此。 在今天的場次裡面我除了介紹這個新功能外，我也將介紹在 AI 的時代裡的軟體開發與分析設計裡面，我怎麼樣利用 mermaid 來提升開發的生產力。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "KyleShen",
                    Name = "沈宏洲 Kyle",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/KyleShen.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "現任微軟最有價值專家，CSM/CSPO，任職過軟體、教育、物流產業，於新創打滾多年，STUDY4 技術社群核心成員，定期舉辦各種領域的技術研討會。<br/>曾於許多大型研討會擔任講者，包含 Hello World Dev Conference、Agile Summit、Microsoft DevDays Asia、.NET Conf、Global Azure Bootcamp、MOPCON",
                    Topic = "數據驅動：研發效能與產品價值共舞",
                    TopicOutline = "在產品開發與研發管理的世界裡，數字固然重要，但真正的關鍵在於這些數據背後代表的「價值」。本場演講將帶您從多角度重新理解效能與成果的關係——不再只是量化產出 (Output)，而是看見帶來影響的成果 (Outcome)。<br/><br/>講者將以跨足新創與大型企業的實務經驗，分享如何讓研發效能與產品指標緊密結合，打造以資料為基礎的決策文化。我們將探討如何拆解團隊生產力成為可衡量要素、導出代表團隊健康度的「魔術數字」，並透過多維度分析框架，讓數據成為持續改善與創造價值的工具。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Derek",
                    Name = "陳岳澤 Derek",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Derek.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "擁有敏捷教練、產品經理、軟體工程師的多元背景，擅長從多方視角，協助團隊提升產品價值與研發效能。曾參與多個跨職能團隊，成功推動 Scrum、Kanban 與大規模敏捷框架落地。熱衷於產品的探索與交付，並樂於陪伴團隊進行敏捷轉型，協助組織打造更具韌性的產品團隊。",
                    Topic = "數據驅動：研發效能與產品價值共舞",
                    TopicOutline = "在產品開發與研發管理的世界裡，數字固然重要，但真正的關鍵在於這些數據背後代表的「價值」。本場演講將帶您從多角度重新理解效能與成果的關係——不再只是量化產出 (Output)，而是看見帶來影響的成果 (Outcome)。<br/><br/>講者將以跨足新創與大型企業的實務經驗，分享如何讓研發效能與產品指標緊密結合，打造以資料為基礎的決策文化。我們將探討如何拆解團隊生產力成為可衡量要素、導出代表團隊健康度的「魔術數字」，並透過多維度分析框架，讓數據成為持續改善與創造價值的工具。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "BaoChengyou",
                    Name = "鮑承佑",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/鮑承佑.jpg",
                    BlogUrl = "https://linktr.ee/windperson",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "本人於 2007 年底投身資訊業，從原本寫 Java，2009 年開始接觸 WPF、Silverlight 的 C# 桌面應用程式開始投入 .NET 開發，之後於資拓宏宇擔任軟體專案工程師，於 2014 年投入遊戲業在台灣卡普空擔任開發組組長，2018 到 2023 上半在 XR 領域相關新創擔任 CTO。<br/>Unity、Xamarin/MAUI、ASP.NET Core、Blazor、Azure SignalR 等前後端與 Azure 雲端開發技術都略懂略懂，但抓 bug比較在行。",
                    Topic = "地端AIAgent+AutoGen, Token Intelligence無極限",
                    TopicOutline = "介紹多種在地端跑 LLM 模型的方法和使用 AutoGen for .NET 以 C# 打造自己的地端AI小精靈",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                   Id = "RyanChung",
                   Name = "Ryan Chung",
                   JobTitle = "Microsoft MVP",
                   PictureUrl ="./img/speakers/Ryan Chung.jpg",
                   BlogUrl = "",
                   FacebookUrl = "",
                   TwitterUrl = "",
                   LinkedinUrl = "",
                   Introduction = "Ryan Chung，行動開發學院 MobileDev.TW創辦人，曾獲微軟人工智能大賽特別獎，目前為製造業上櫃公司AI顧問、微軟MVP Summit Pre-Day / Reactor / DevDaysAsia / .NET Conf Taiwan講師、中央大學AI學程兼任講師、元智大學資工系兼任助理教授級專業技術人員。專長於雲端生成式AI應用整合開發，使用 Azure OpenAI / Azure AI / Google Gemini AI / Amazon Bedrock AI。2022年起，獲選為微軟AI MVP 人工智慧最有價值專家。",
                   Topic = "MS Ignite 2025舊金山現場直擊 - 最新趨勢大剖析",
                   TopicOutline = "微軟在每年的十一月份，會舉辦全球Ignite大會，今年在舊金山舉辦。究竟在年底的活動中，微軟還能端出什麼樣的牛肉？AI Agent 與 MCP還有哪些應用的可能性？且聽來自Ryan的現場直擊！",
                   Room = "",
                   Track = "",
                   SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                   SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                   IsShow = true,
                   Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "RuddyLee",
                    Name = "李智樺",
                    JobTitle = "91APP 敏捷教練",
                    PictureUrl ="./img/speakers/Ruddy Lee.jpg",
                    BlogUrl = "https://ruddyblog.wordpress.com/",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "具有超過40年的工程師經歷，擅長敏捷開發，著作有 :精實開發與看板方法、Windows Azure雲端開發、WF 工作流程引擎程式設計、微軟 VSTS 開發實戰等書。<br/>為專業的軟體開發顧問、Scrum及看板課程教學的講師。近年來；致力於推廣「開發者體驗」，專注於協助開發團隊與研發工程師的自我成長及敏捷開發實踐。曾擔任過多家資訊公司的研發部經理。現任集英信誠Mentor Trust 公司的敏捷顧問。為經常往返於二岸的精實佈道師。",
                    Topic = "AI時代工程師的軟技能",
                    TopicOutline = "在 AI 快速滲透開發流程的今天，工程師的價值不應再侷限於「寫多少程式」，而是要提升到以顧問式思維來解題。本場演講以「AI時代的軟技能」為題，結合教育學者提出的心智框架，探討工程師在新時代所需的四大能力：認知、社會、自我與實踐。我將分享自己在顧問工作中常用的解題流程:「問題 → 痛點 → AI加速／敏捷落地 → 驗證 → 擴散」，示範如何讓 AI 融入敏捷小迭代，成為團隊的推進器。透過實際案例與方法，協助大家在 AI 時代找到持續成長的定位。",
                    Room ="",
                    Track ="",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                   Id = "DemoFan",
                   Name = "Demo Fan",
                   JobTitle = "Microsoft MVP",
                   PictureUrl ="./img/speakers/DemoFan.jpg",
                   BlogUrl = "",
                   FacebookUrl = "",
                   TwitterUrl = "",
                   LinkedinUrl = "",
                   Introduction = "微軟最有價值專家（MVP）連任 18 屆，長期投入 .NET 技術推廣與 Web 開發教育，熱衷用有趣的方式講技術。目前在 SkillTree 程式教育品牌中教人寫程式，也在 twMVC 社群裡陪大家一起成長、不孤單。",
                   Topic = "地表最強 IDE Visual Studio 2026 來了！",
                   TopicOutline = "Visual Studio 的定位、Visual Studio 在 AI 世界如何生存、Visual Studio 2026 的新功能介紹",
                   Room = "",
                   Track = "",
                   SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                   SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                   IsShow = true,
                   Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "Summit",
                    Name = "孫玉峰",
                    JobTitle = "台灣角川 數據架構師",
                    PictureUrl ="./img/speakers/孫玉峰.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "Summit is a seasoned data scientist with 10+ years working experiences providing actionable insights and intelligent data products across various industries.<br/><br/>RecSys, AdTech, MLOps<br/>Active OSS Contributor (Apache Airflow, AutoGPT)<br/>Microsoft Most Valuable Professionals (Data Platform/AI) since 2017",
                    Topic = "AI Agent 也要技術選型嗎？深入了解語言模型跑分與評測資料集",
                    TopicOutline = "介紹現行大型／多模態語言模型評測方式的目的及遇到的瓶頸，透過文獻回顧來討論從更多面向（認知、知識、公平、資安⋯⋯等）去衡量語言模型能力的思路，亦可作為開發者在選用語言模型時的技術選型階段能夠參考的指引與架構。另外也介紹實作語言模型評測資料集時會遇到的挑戰以及處理方式。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                // new SpeakerModel {
                //    Id = "BenChen",
                //    Name = "陳奎銘",
                //    JobTitle = "Principal Data Scientist @ OneLab",
                //    PictureUrl ="./img/speakers/BenChen.jpg",
                //    BlogUrl = "",
                //    FacebookUrl = "",
                //    TwitterUrl = "",
                //    LinkedinUrl = "",
                //    Introduction = "有幸成為微軟 AI 領域 MVP 的資料科學家，致力於用資料科學解決各個領域的疑難雜症，舉凡投資、生技醫療和其他傳統產業，都有相關實務處理的經驗。除此之外，不定期也會接到授課的邀約，協助不同組織機構初探數位轉型，進入資料科學的世界。同時，我也是 R-Ladies Taipei Co-organizer，正嘗試努力每個月都舉辦活動，繼續延續社群的活力。",
                //    Topic = "TBD",
                //    TopicOutline = "TBD",
                //    Room = "",
                //    Track = "",
                //    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //    IsShow = true,
                //    Tags = new string[]{ "CM", "HackMD" },
                // },
                 new SpeakerModel {
                    Id = "Daisy",
                    Name = "林育岑（Daisy）",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Daisy.jpeg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "曾任生技、醫療、軟體產業，歷經多年新創磨練，從新創的快速變革中淬煉成長，並不斷探索如何運用創新方法提升工作效率與樂趣！<br/><br/>在職涯早期，也與敏捷結下不解之緣，並將這份精神應用於團隊協作。曾與技術主管緊密合作，成功帶領面臨挑戰的軟體開發團隊回歸正軌，並將敏捷管理導入地方創生團隊，提升工作效能。<br/><br/>此外，也參與多項團隊翻譯，包括 《中華民國專案管理國家標準 CNS21500、CNS21502》、《ScrumMastery：從優秀到卓越的僕人式領導力》 以及 《喪屍 Scrum 生存指南：邁向真敏捷的復原之路》，這些經驗讓我對敏捷與流程優化有著更全面的理解。<br/><br/>現任 Google Developer Group Taichung 組織者 (Organizer)，透過持續探索與應用 AI 的無限可能，相信可以共同打造更智慧、更高效的工作模式，讓每一段投入都更有價值。<br/><br/><br/>敏捷經驗：<br/><br/>1、經歷過多個軟體開發問題團隊，透過導入敏捷，與技術主管合作，帶領團隊一步步發現、釐清問題、邁向正軌。<br/><br/>2、非軟體產業：<br/><br/>(1)2022-2024年，協助3個地方創生團隊，引導團隊導入敏捷式管理，走出經營困境，更有效能帶領團隊前進。<br/><br/>(2)透過敏捷大型框架Less，完成CNS21500、CNS21502之翻譯。<br/><br/>(3)透過敏捷大型框架Nexus，完成ScrumMastery：從優秀到卓越的僕人式領導力之翻譯。",
                    Topic = "告別敏捷「假成功」：將承諾轉為可靠的價值交付",
                    TopicOutline = "您是否厭倦了那種「看似有在跑，實則原地踏步」的專案？<br/><br/>許多組織的敏捷已經變成一個空有儀式、沒有精神的軀殼—「殭屍 Scrum」。在這種狀態下，團隊開會很勤快，工作量「點數」也算得很高，但實際上，交出的東西客戶不買單，而且到處是程式錯誤。<br/><br/>我們將一起看到敏捷流程中常見的陷阱：為什麼只看「衝刺速度」會讓團隊疲於奔命，最後卻犧牲了品質？並一起從「只求交差」轉向「交付價值」！",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                 },
                 new SpeakerModel {
                    Id = "AlanTsai",
                    Name = "Alan Tsai",
                    JobTitle = "微軟最有價值專家",
                    PictureUrl ="./img/speakers/Alan Tsai.jpg",
                    BlogUrl = "https://blog.alantsai.net/",
                    FacebookUrl = "http://fb.alantsai.net/",
                    TwitterUrl = "http://twitter.alantsai.net/",
                    LinkedinUrl = "http://linkedin.alantsai.net/",
                    YouTubeUrl = "http://yt.alantsai.net/",
                    Introduction = "熱愛學習、分享與教學，專精於 .NET (Core)、ASP.NET Core、Azure、架構設計、Container、DevOps、Bot Framework (chatbot), ==GitHub Copilot== 等領域。<br/>堅信教學是最佳的學習方式，喜歡將新知轉化為文章、影片、課程與演講，並在「Alan Tsai 的學習筆記」部落格分享。<br/>同時，也熱衷於翻譯軟體/文章，目前已翻譯了兩本書。<br/>榮幸擔任微軟最有價值專家 (MVP) - Azure和微軟認證講師 (MCT)，並擁有數十張與Azure相關的證照。<br/>除了工作之外，我也非常喜歡參與和協助社群活動，是Study4.TW的成員之一。閒暇時，我喜歡閱讀小說和打打手遊。<br/>如果有機會參加活動，歡迎找我聊聊哦！<br/>期待與大家建立聯繫，一同學習和成長！",
                    Topic = "API Design First：設計先行但實作跑偏？聊聊設計與實作的一致性挑戰",
                    TopicOutline = "隨著 AI 與 Cloud Native 的普及，應用程式之間透過 RESTful API 溝通已經是日常。 <br/>要「會寫 API」不難，但要「設計出好 API」卻是一門藝術。<br/>然而，設計得再完整，若實作走樣，成果往往大打折扣。<br/>即使有了完善的 API 規格，如何確保開發出來的實作與設計一致，仍然是一大挑戰。<br/><br/>在這場分享中，我們將一起：<br/><br/>1. 理解設計與實作之間為何容易出現落差<br/>2. 探索更快速驗證 API 規格與實作的方法<br/>3. 建立團隊協作中更可靠的 API 開發流程",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                 },
                new SpeakerModel {
                    Id = "MarcusTung",
                    Name = "Marcus Tung",
                    JobTitle = "微軟最有價值專家",
                    PictureUrl ="./img/speakers/Marcus Tung.jpg",
                    BlogUrl = "https://marcus116.blogspot.com/",
                    FacebookUrl = "https://www.facebook.com/marcustung.tech",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "現任微軟最有價值專家（Developer Technologies）和 DevOps Taiwan 技術社群志工，樂於研究與分享 後端技術，將學習與實踐的心得記錄在個人部落格 m@rcus 學習筆記上，並於粉絲團不定期分享技術開發與 Observability 相關新知。",
                    Topic = "Spec-kit x O.D.D：打造 AI 時代的 .NET 開發新選擇？",
                    TopicOutline = " AI 加速了開發流程，卻也讓「品質」與「透明度」成為新的挑戰。 本場分享將介紹如何結合 Spec-Kit 的規格驅動開發（Spec-Driven Development, SDD） 與 可觀測驅動開發（Observability-Driven Development, ODD），讓 .NET 開發者能從需求定義到系統行為驗證，打造一條「AI 寫得快、系統看得清」的開發流程，讓每一次上線都能被觀測、被驗證、被信任。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "BillChung",
                    Name = "Bill Chung",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Bill Chung.jpg",
                    BlogUrl = "https://www.dotblogs.com.tw/billchung",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "Microsoft MVP，熱愛寫程式與講故事",
                    Topic = "C# 14 新功能",
                    TopicOutline = "每年 C# 改版都有新驚喜，今年又帶來甚麼方便好用的功能？",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                 new SpeakerModel {
                     Id = "JamesTsai",
                     Name = "James Tsai",
                     JobTitle = "微軟最有價值專家",
                     PictureUrl ="./img/speakers/James Tsai.jpg",
                     BlogUrl = "",
                     FacebookUrl = "",
                     TwitterUrl = "",
                     LinkedinUrl = "",
                     Introduction = "現任 Microsoft MVP - Developer Technologies (2015~) 與 骨架資訊有限公司的技術總監。從 10 年多前開始接觸 .NET 程式開發後，經歷過撰寫各家行動平台的 App 與 Azure 雲端應用服務整合。Blog: https://xamarintech.blogspot.tw 與點部落: https://dotblogs.com.tw/jamestsai，內容涵蓋 Xamarin、Azure 服務與 Microsoft 365 的 Intune 相關應用等開發紀錄。並持續經營當前台灣最活耀的 Xamarin 社群 (Facebook 社群名稱: Xamarin Asia Developers)，與專注於跨平台應用開發與 CI/CD 整合、企業行動化資料保護…等的技術的研究與推廣。",
                     Topic = "莫名其妙就跟世界級的 OpenSource 專案攪和了!? ",
                     TopicOutline = "當 .NET 開發能跨平台運用後，開發人員要達成 Write once, Run anywhere! 是 '真的' 可以被實踐的。由於裝置端的產品程式可能會有各種不同的平台需要面對，能透過開發一套 Code 並完成佈署到各時期所發行不同平台的裝置端上運作，則是開發人員最為引以為傲的事。<br/>面對裝置端應用 UI 運作需透過疊合不同層面的顯示，讓用戶與使用者在與裝置端互動時都能保有良好的使用體驗，則是產品開發人員追求的極致發展。<br/>本議程將來聊聊這樣的開發經驗的落實，與其中運用的核心技術並完成跨平台運作的發展。",
                     Room = "",
                     Track = "",
                     SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                     SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                     IsShow = true,
                     Tags = new string[]{ "CM", "HackMD" },
                 },
                new SpeakerModel {
                    Id = "CaiWenlong",
                    Name = "蔡文龍",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/蔡文龍.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "連續17年微軟最有價值專家(AI + Developer 雙領域 MVP)、專業電腦圖書作家，著有超過140本以上電腦書籍，現職於僑光科技大學多媒體與遊戲設計系副教授，專長雲端應用程式、人工智慧軟體服務、遊戲設計，同時受聘各公民營企業、內訓課程開發規劃。",
                    Topic = "AI Agent啟動指南：全面解析Responses API與Realtime API",
                    TopicOutline = "本場講座將帶您深入解析 Responses API 與 Realtime API 的核心能力，讓 AI 不僅能回應與處理多模態內容，還能主動感知、即時互動與執行任務。透過實際程式示範，將引導你打造能「動起來」的智慧助理，為開發 AI Agent 奠定關鍵基礎。",
                    Room ="",
                    Track ="",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM" },
                },
                new SpeakerModel {
                    Id = "OuZhixin",
                    Name = "歐志信",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/歐志信.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "連續17年微軟最有價值專家、資訊圖書作者，現任職於電信業，協助政府機關與企業客戶導入生成式AI、智慧影像辨識（人臉辨識、人形辨識）應用。",
                    Topic = "AI Agent啟動指南：全面解析Responses API與Realtime API",
                    TopicOutline = "本場講座將帶您深入解析 Responses API 與 Realtime API 的核心能力，讓 AI 不僅能回應與處理多模態內容，還能主動感知、即時互動與執行任務。透過實際程式示範，將引導你打造能「動起來」的智慧助理，為開發 AI Agent 奠定關鍵基礎。",
                    Room ="",
                    Track ="",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                   Id = "Shanna",
                   Name = "Shanna",
                   JobTitle = "",
                   PictureUrl ="./img/speakers/shanna.jpg",
                   BlogUrl = "",
                   FacebookUrl = "",
                   TwitterUrl = "",
                   LinkedinUrl = "",
                   Introduction = "前端工程師，目前是Google Developr Group Taichung Organizer<br/>，喜歡學習分享及討論技術，時常出沒在各社群場合。",
                   Topic = "AI Foundry X Github Copilot 帶你快速打造第一個 .NET的AI應用程式",
                   TopicOutline = "Azure AI Foundry 提供了一個完整且全面的平台，讓開發者從建置、測試到部署 AI 應用程式一把抓。<br/><br/>近年來開發人員常陷入「Vibe Coding」的困境—與 AI 對話像猜謎、程式碼品質不穩定、專案意圖難以追溯。<br/><br/>本次議程將帶大家使用AI Foundry ，示範如何利用其功能來支援你的 AI 專案，並搭配Github Copilot ，體會使用Vibe Coding的正確姿勢。<br/><br/>您將學習如何使用 AI 模型、管理提示和流程安排、實施 AI 系統的評估和測試，以及如何自信地將 AI 應用程式部署到生產環境。",
                   Room = "",
                   Track = "",
                   SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                   SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                   IsShow = true,
                   Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                   Id = "LinZhengxiang",
                   Name = "ATai",
                   JobTitle = "",
                   PictureUrl ="./img/speakers/ATai.jpg",
                   BlogUrl = "",
                   FacebookUrl = "",
                   TwitterUrl = "",
                   LinkedinUrl = "",
                   Introduction = "現任微軟領域最有價值專家，樂於研究與分享新技術，喜歡使用各項網頁技術解決各項問題。主要專研 .NET 相關 Solution，以及 Angular & Vue.js 等前端技術，並在第十二屆 iT 邦幫忙鐵人賽中的 Modern Web 組獲得佳作。於 2022 年出版 ASP.NET Core 6 實戰守則：超易懂的跨平台開發入門教學，並榮登天瓏年度排行第二名，目前致力於各種應用類型AI落地以及AI應用程式的開發，期待能探索更多不同可能性",
                   Topic = "AI Foundry X Github Copilot 帶你快速打造第一個 .NET的AI應用程式",
                   TopicOutline = "Azure AI Foundry 提供了一個完整且全面的平台，讓開發者從建置、測試到部署 AI 應用程式一把抓。<br/><br/>近年來開發人員常陷入「Vibe Coding」的困境—與 AI 對話像猜謎、程式碼品質不穩定、專案意圖難以追溯。<br/><br/>本次議程將帶大家使用AI Foundry ，示範如何利用其功能來支援你的 AI 專案，並搭配Github Copilot ，體會使用Vibe Coding的正確姿勢。<br/><br/>您將學習如何使用 AI 模型、管理提示和流程安排、實施 AI 系統的評估和測試，以及如何自信地將 AI 應用程式部署到生產環境。",
                   Room = "",
                   Track = "",
                   SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                   SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                   IsShow = true,
                   Tags = new string[]{ "CM", "HackMD" },
                },
                 new SpeakerModel {
                     Id = "EvanceKao",
                     Name = "Evance Kao",
                     JobTitle = "",
                     PictureUrl ="./img/speakers/Evance Kao.jpg",
                     BlogUrl = "",
                     FacebookUrl = "",
                     TwitterUrl = "",
                     LinkedinUrl = "",
                     Introduction = "從天氣預報斜槓到軟體開發，從每天看雲轉變為服務上雲，喜歡從不同角度看同一件事情、抽象化各種業務邏輯、製造小輪子以揣摩米其林輪胎的設計。大多鑽研 DevOps (專注在 CI/CD)、系統架構與雲端服務，實務上則有 6 年以上的雲端架構設計、開發及維護經驗，並具有公有雲助理級證照。<br/>現在專注於商品搜尋與推薦領域，嘗試以 AI 讓大家能更好的買買買。<br/>過去分享：<br/>* 更好的開發體驗 - 建造 SDK 接上 API 的腿 @ .NET Conf Taiwan 2022<br/>* 容器化你的 .NET 生產線 @ STUDY4 2023 小聚",
                     Topic = "Agent-Driven 個人化商品搜尋系統",
                     TopicOutline = "在這場演講中，我們將把「會懂你的搜尋」真正落地：從商品向量到使用者向量，以 Azure 與最新的 Microsoft Agent Framework 把同一個查詢轉化為因人而異的結果與排序，讓你的系統不只看見關鍵字，更能理解使用者的真正意圖。<br/><br/>🔭 系統架構與流程：以 Azure × Microsoft Agent Framework 打造一站式流程，從資料進來、向量更新、查詢服務到回傳解釋，一條龍落地。<br/><br/>🧱 向量建置與治理：高效率、低成本地建置與維運商品向量與使用者向量，涵蓋批次/即時處理、版本控管與回滾策略。<br/><br/>🔍 個人化檢索排名：盤點多種檢索策略，帶你學會如何比較方法、量測效益並持續最佳化。<br/><br/>無論你是搜尋與推薦的新手，或正計畫把個人化 AI 導入系統或服務的工程師、架構師與技術主管，這場將提供清楚的實作路線與可複製的實踐；不只適用於商品搜尋，也能延伸到客服與知識庫系統。",
                     Room = "",
                     Track = "",
                     SessionStart = new DateTime(2022, 12, 17, 0, 0, 0),
                     SessionEnd = new DateTime(2022, 12, 17, 0, 0, 0),
                     IsShow = true,
                     Tags = new string[]{ "CM", "HackMD" },
                 },
                new SpeakerModel {
                    Id = "JimmyLiao",
                    Name = "Jimmy Liao",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/JimmyLiao.jpg",
                    BlogUrl = "https://jimmyliao.net/",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "https://www.linkedin.com/in/jimmyliao/",
                    Introduction = "Jimmy Liao 先後就職於 Appier/Microsoft/InfuseAI/IBM 。專業技能橫跨應用程式、手機應用、後端開發、廣告投放、機器學習專案開發，近期致力於 Generative AI 以及相關應用推廣，協助客戶技術落實及技術諮詢。目前為 Google 社群開發專家 (AI GDE) 與微軟社群開發專家 (AI MVP) 。<br/><br/>日常生活就是跑步，曾經以跑步為通勤工具之一 (單程 20+ km)。<br/><br/>As the Google AI GDE and Microsoft AI MVP and with 20+ years experience as technical lead in large enterprise and startup. Jimmy Liao act as GenAI Solution Architect now. He focus on solution architecture design, PoC, Production with modern solutions. Also for Generative AI/AI Application landing, education, and communities.",
                    Topic = "Azure AI Foundry 上的企業級 Agent 開發實踐：運用 Microsoft Agent Framework 與 Codex CLI 打造高效能多代理協作系統",
                    TopicOutline = "本實踐將圍繞以下三個核心組件進行深入探討與實戰演示：<br/><br/>Microsoft Agent Framework： 我們將利用其強大的 多代理協調 (Multi-Agent Orchestration) 能力，結合類型安全（Type Safety）和靈活的工作流程（Workflows），構建複雜的協作邏輯。<br/><br/>Codex CLI： 演示如何利用這個命令行工具，將 Agent 能力直接引入 DevOps 和編程自動化 流程中，實現如自動程式碼重構、測試生成或 Pull Request 創建等高效能的 Agent 任務執行。<br/><br/>Azure AI Foundry： 作為整個系統的 底層平台，我們將利用其提供的模型部署、資源管理、監控與治理（Observability and Governance）功能，確保整個多代理協作系統在企業環境中安全、穩定、高效地運行。<br/><br/>透過本實踐，參與者將能獲得一套完整的 「Agent 開發、部署與自動化」 解決方案藍圖，為企業的智慧化升級奠定堅實的技術基礎。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "ChrisLiu",
                    Name = "Chris Liu",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Chris Liu.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "前某義大利餐廳行政主廚，曾於兩間台灣金流界龍頭任職，也曾擔任過某電子支付公司研發部主管，現為 Geek & Nerd Studios CEO 喜歡協助客戶完成技術導入，對他而言程式就跟料理一樣 keep learning, keep your knife sharpen。",
                    Topic = "Building Intelligent Apps with .NET",
                    TopicOutline = "人工智慧正重新定義應用程式的開發方式，而 .NET 提供整合 AI 的強大工具。本次議程將介紹如何運用 .NET 的 AI 功能與 Microsoft.Extensions.AI，串接大型語言模型、語意搜尋與各種智慧功能，並示範雲端與本地模型的應用模式，協助你打造更聰明、更能回應使用者需求的應用程式。開始你的 .NET AI 開發之旅吧。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                 new SpeakerModel {
                     Id = "Ahdaa",
                     Name = "Ahdaa",
                     JobTitle = "",
                     PictureUrl ="./img/speakers/Ahdaa Yeh.jpg",
                     BlogUrl = "",
                     FacebookUrl = "",
                     TwitterUrl = "",
                     LinkedinUrl = "",
                     Introduction = "水映工作坊創辦人。於企業中，以資訊顧問、講師等身份投入協助各種跨場域與跨不同領域所需要之軟體整合，亦善用 AI 加速產品開發或是解決零散問題。<br/><br/>於社群中，是一個愛投入技術研究的 NPC，以 Flutter/Android/Firebase 為主要分享主軸，常出沒於 Google Developer Group Taichung/Taichung 的 Organizer",
                     Topic = "從規格與代理部署的圓舞曲",
                     TopicOutline = "開發者在和 AI 協作的過程，也是一種體驗。體驗一個給予想法、互動調整，再到部署，這樣的流程能夠穩定且讓 AI 幫我們部署。<br/>因此慢慢地開始有了 「規格驅動 (Specification-Driven)」，而有規格就一勞永逸嗎？為什麼都有 Agent 了，為什麼有些功能，甚至部署可能都要手工作業呢？<br/>這個講次和各位分享自己的觀察，以及聊聊 Agent 可為以及不可為之處。",
                     Room = "",
                     Track = "",
                     SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                     SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                     IsShow = true,
                     Tags = new string[]{ "CM", "HackMD" },
                 },
                new SpeakerModel {
                    Id = "JrtingShiau",
                    Name = "蕭晊莛",
                    JobTitle = "Technical Manager",
                    PictureUrl ="./img/speakers/Jrting Shiau.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "目前任職於新加坡商鈦坦科技擔任 Technical Manager 一職，目前專注於探索 AI 應用的可能性",
                    Topic = "Chat Bot 的隱藏知識庫：RAG 以外的第二選擇",
                    TopicOutline = "當我們談到企業內部的 Chat Bot，RAG 往往是第一個被想到的解法。但在真實世界中，企業的 Domain 知識並不只存在於文件或知識庫裡，更多時候，它深埋在程式碼邏輯中：商品的過濾條件、驗證規則、業務流程 API……這些才是真正決定 Bot 是否能給出正確答案的關鍵。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                 new SpeakerModel {
                    Id = "TimLai",
                    Name = "Tim Lai",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Tim Lai.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "擁有 20 年軟體開發與系統架構設計經驗，熟悉專案管理與敏捷方法論，目前主要協助企業客戶導入 Azure DevOps，並提供專業教育訓練，協助團隊提升敏捷開發與自動化部署的能力。熱衷於推動 AI 技術與現代開發流程的整合，將 GitHub Copilot 等 AI 工具融入 DevOps 實務，讓團隊協作更快速、有效且具有品質。",
                    Topic = "碼農出擊! GitHub Copilot 帶你飛：打造超效率開發術",
                    TopicOutline = "GitHub Copilot 是市面上 CP 值最高的開發助手，不僅支援多種 AI 模型，還能靈活自訂 VSCode 裡的 Instructions、Prompt files 和 Chat Modes，讓我們用最快的速度完成高品質程式碼開發。本次演講也會介紹實用的 Copilot CLI，並分享實際案例，帶大家輕鬆提升開發效率，成為你最值得信賴的開發夥伴！。",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                 }
            };

            return speakers;
        }
    }
}
