using dotnetConf2025.Shared.Models;

namespace dotnetConf2025.Shared.Services
{
    public class SpeakerService
    {
        public IEnumerable<SpeakerModel> GetSpeakers()
        {
            var speakers = new List<SpeakerModel> {
                new SpeakerModel {
                    Id = "WillHuang",
                    Name = "Will Huang",
                    JobTitle = "多奇數位創意 技術總監",
                    PictureUrl ="./img/speakers/Will 保哥.jpg",
                    BlogUrl = "http://blog.miniasp.com/",
                    FacebookUrl = "https://www.facebook.com/will.fans/",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "現任「多奇數位創意有限公司」技術總監。2024 年榮獲 GenAI 方向的 Google Developer Expert (GDE) 開發專家。2019 獲選微軟技術社群區域總監 (Microsoft Regional Director)。2018 年榮獲 Angular 方向的 Google Developer Expert (GDE) 開發專家。連續 18 度當選微軟最有價值專家(MVP)。熟悉 Generative AI、Angular、JavaScript、.NET、C#、Java、Go、Docker、Kubernetes 相關技術。擅長 DevOps 與組織文化建立、軟體團隊建構與管理。熱愛分享知識。",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                // new SpeakerModel {
                //     Id = "DavidTung",
                //     Name = "David Tung",
                //     JobTitle = "光岩資訊資深技術顧問",
                //     PictureUrl ="./img/speakers/David Tung.jpg",
                //     BlogUrl = "http://studyhost.blogspot.tw/",
                //     FacebookUrl = "http://www.facebook.com/DotNetWalker/",
                //     TwitterUrl = "",
                //     LinkedinUrl = "",
                //     Introduction = "光岩資訊資深技術顧問、歷屆微軟 TechDays、TechED 研討會講師、連續 14 年榮獲微軟最有價值專家 (MVP)、LINE API Expert(LAE)，專長領域跨及.NET開發技術、Azure DevOps、AI、ChatBot...熟悉 BPM、APS、ERP…等企業應用資訊系統之建置與導入。David 是敏捷開發與 DevOps 的熱愛者，打從 Apple II 時代開始闖蕩江湖至今，在資訊業各領域均有參與。做過 MIS/IT、當過 RD、帶過專案、團隊、也賣過軟體，寫過（這年頭已經消失了的）雜誌專欄、長年擔任企業訓練講師與顧問，出過一堆書……打從沒有物件導向，沒什麼所謂軟體生命週期管理的年代，一路經歷了無數個壯觀的大小瀑布與千瘡百孔的雷與坑、一直到今天，依舊還是一個喜歡寫 Code 的人...",
                //     Topic = "TBD",
                //     TopicOutline = "TBD",
                //     Room = "",
                //     Track = "",
                //     SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //     SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //     IsShow = true,
                //     Tags = new string[]{ "CM", "HackMD" },
                // },
                new SpeakerModel {
                    Id = "EdwardKuo",
                    Name = "Edward Kuo",
                    JobTitle = "Microsoft Regional Director",
                    PictureUrl ="./img/speakers/Edward Kuo.jpg",
                    BlogUrl = "https://profile.edwardkuo.dev/",
                    FacebookUrl = "https://www.facebook.com/EdwardKuo.Teched",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "現任美商科技製造公司資訊處資深經理，兼具 Microsoft Regional Director 與 Microsoft Azure MVP 身分，長期投身技術社群與產業實務。擅長雲端架構設計、工業 4.0、供應鏈系統、AI/ML 與 DevOps 解決方案，善於以多元觀點串聯業界需求與技術落地。熱衷於知識分享，活躍於各大技術研討會、社群論壇及企業訓練，亦為多所大學客座講師。致力推動企業數位轉型，持續促進技術交流與社群成長，協助更多團隊實現創新價值。",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                // new SpeakerModel {
                //     Id = "AndrewWu",
                //     Name = "Andrew Wu",
                //     JobTitle = "91APP 首席架構師",
                //     PictureUrl ="./img/speakers/Andrew Wu.jpg",
                //     BlogUrl = "https://columns.chicken-house.net/",
                //     FacebookUrl = "https://www.facebook.com/andrew.blog.0928/",
                //     TwitterUrl = "",
                //     LinkedinUrl = "",
                //     Introduction = "現任職於大型軟體開發團隊的架構師，負責核心產品的服務化，與內部產品開發團隊的架構改善等任務。在過去的 20 年工作經驗，主要都專注於 Microsoft .NET Framework 開發 SaaS , B2B2C 的雲端服務。我專長的領域包括: 軟體工程，物件導向設計，分散式系統架構設計，平行處理，API 設計 及 微服務導向架構設計 (microservices) 等。<br/>我樂於分享技術新知與開發的經驗，常在各大研討會或是在社群活動上分享經驗。同時我也有撰寫部落格文章的習慣，希望能累積我的經驗給需要的夥伴們。我深信知識是越分享越精進的，這也是支持我自 2004 至今連續 20 年不間段分享文章的動力來源。<br/>個人經歷:<br/>- 現任 91APP, 首席架構師 Chief Architect<br/>- 榮獲 Microsoft MVP 微軟最有價值專家 獎項,2016 ~ 2025<br/>- 擔任多次 Microsoft Azure Cafe, TechDays, TechEd, DevOpsDays Taiwan, .NET Conf 等大型研討會講者，與相關 Azure PaaS 雲端系列課程與企業內訓講師<br/>https://columns.chicken-house.net/about/",
                //     Topic = "TBD",
                //     TopicOutline = "TBD",
                //     Room = "",
                //     Track = "",
                //     SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //     SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //     IsShow = true,
                //     Tags = new string[]{ "CM", "HackMD" },
                // },
                // new SpeakerModel {
                //     Id = "YinSangzhi",
                //     Name = "尹相志",
                //     JobTitle = "",
                //     PictureUrl ="./img/speakers/尹相志-AI.jpg",
                //     BlogUrl = "",
                //     FacebookUrl = "",
                //     TwitterUrl = "",
                //     LinkedinUrl = "",
                //     Introduction = "DataDecision.ai數據科學家，大數據行業經歷今年第25年，於2002年成立台灣第一家大數據顧問公司asiaMiner，曾經協助台灣大大型電信公司（中華電信、遠傳電信、台灣大哥大）、銀行（中國信託、台新、台灣銀行、元大、新光、萬泰...等、零售業（特力屋、屈臣氏，7-11）...等企業導入數據科學相關產業應用。也是臺灣微軟在數據科學領域的特約講師，曾獲選2006~2017年微軟最有價值專家(MVP)，於2015~2016年曾兼任上海華院數據（中國第一家大數據顧問公司）之首席數據科學家，於任內發起中國首次國際人工智能競賽「BOT (Brain of things) Shanghai 2016」，同時也擔任2016年與2017年的賽題設計。現任中興保全科技、光寶科技、啟雲科技之企業顧問",
                //     Topic = "TBD",
                //     TopicOutline = "TBD",
                //     Room = "",
                //     Track = "",
                //     SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //     SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //     IsShow = true,
                //     Tags = new string[]{ "CM", "HackMD" },
                // },
                new SpeakerModel {
                    Id = "IanChan",
                    Name = "陳葵懋 Ian",
                    JobTitle = "微軟最有價值專家",
                    PictureUrl ="./img/speakers/Ian.jpg",
                    BlogUrl = "https://medium.com/playtech",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "https://www.linkedin.com/in/codeian/",
                    Introduction = "目前任職於一等一科技，同時也是微軟 AI 人工智慧最有價值專家（MVP）與微軟認證講師（MCT）。專注於 .NET、Azure 、容器化、雲/地端生成式AI應用解決方案，曾受邀在 Microsoft TechDay、DevDays、.NET Conf Taiwan 、MWC、MOPCON 等大型技術研討會擔任講師，分享業界實戰心法。近年聚焦生成式 AI 、RAG與 AI Agent 的研究，具有實務上的實踐以及培訓經驗。<br/>出版多本生成式AI共同著作：<br/>• AI Agent 奇幻旅程：MCP 通往異世界金鑰（含最新 OpenAI GPT-5 範例）<br/>• Python原力爆擊：OpenAI / Gemini / AWS / Ollama生成式AI應用新手指南<br/>• LangChain 奇幻旅程：OpenAI x Gemini x 多模態應用開發指南<br/>• 極速 ChatGPT 開發者兵器指南：跨界整合 Prompt Flow 、LangChain 與 Semantic Kernel 框架<br/>• 駕馭 ChatGPT 4: 探索 Azure OpenAI 與 Cognitive Service for Language 開發實踐 （使用 .NET 與 Node.js）",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                // new SpeakerModel {
                //     Id = "KoKo",
                //     Name = "KO KO",
                //     JobTitle = "",
                //     PictureUrl ="./img/speakers/KO KO.jpg",
                //     BlogUrl = "",
                //     FacebookUrl = "https://www.facebook.com/magic.panda.engineer/",
                //     TwitterUrl = "",
                //     LinkedinUrl = "",
                //     Introduction = "Ko Ko 是一位資深的軟體工程師，也連續四年獲得微軟 AI 領域的最有價值專家（Microsoft AI MVP）獎項。他擔任許多技術年會的講者，包含了 COSCUP、ModernWeb、名古屋開源年會、香港開源年會、PyCon APAC、PyCon HK、DevDays Asia 等等的大型年會，累計已超過萬名聽眾。共同著作有《駕馭 ChatGPT 4: 探索 Azure OpenAI 與 Cognitive Service for Language 開發實踐 (使用. NET 與 Node. Js)》一書，拿過天瓏書局暢銷排行榜第二名。經營臉書粉專「大魔術熊貓工程師」。Ko Ko 所撰寫系列文章「一起學習 Azure Machine Learning」是繁體中文圈關於 Azure Machine Learning 最完整的學習資源之一。",
                //     Topic = "TBD",
                //     TopicOutline = "TBD",
                //     Room = "",
                //     Track = "",
                //     SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //     SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //     IsShow = true,
                //     Tags = new string[]{ "CM", "HackMD" },
                // },
                // new SpeakerModel {
                //     Id = "JiaSin",
                //     Name = "陳佳新（奇步老爹）",
                //     JobTitle = "奇步應用有限公司 執行長",
                //     PictureUrl ="./img/speakers/陳佳新.jpg",
                //     BlogUrl = "",
                //     FacebookUrl = "",
                //     TwitterUrl = "",
                //     LinkedinUrl = "",
                //     Introduction = "具備 LINE API Expert 及 Microsoft AI MVP 專家資格，推廣 Chatbot 聊天機器人及 AI 人工智慧技術落地不遺餘力，目前是中部人的聊天機器人小小聚、彰化 AMA 小聚、彰化 Google 技術開發者社團的活動主辦人，致力於提升故鄉彰化乃至中部地區的數位化能力，同時也是「彰化旅行+」的核心成員，來彰化吃喝玩樂歡迎指名！",
                //     Topic = "TBD",
                //     TopicOutline = "TBD",
                //     Room = "",
                //     Track = "",
                //     SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //     SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //     IsShow = true,
                //     Tags = new string[]{ "CM", "HackMD" },
                // },
                // new SpeakerModel {
                //     Id = "BruceChen",
                //     Name = "陳傳興（Bruce Chen）",
                //     JobTitle = "Kingston Senior Engineer",
                //     PictureUrl ="./img/speakers/Bruce Chen.jpg",
                //     BlogUrl = "https://blog.kkbruce.net/",
                //     FacebookUrl = "",
                //     TwitterUrl = "",
                //     LinkedinUrl = "",
                //     Introduction = "由MS-DOS 6.22與Intel 486 DX2-66進入資訊領域，在QBasic寫下第一行Hello World，就愛上了開發的世界，目前任職於遠東金士頓科技擔任資深工程師。現任微軟最有價值專家（Microsoft MVP），喜歡分享技術心得於部落格（https://blog.kkbruce.net），瀏覽量超過七百萬。經常出沒於STUDY4與twMVC社群與其他研討會。合著出版作品有《ASP.NET MVC 4網站開發美學》、《ASP.NET MVC 5網站開發美學》。合譯出版作品有《Martin Fowler的企業級軟體架構模式》。審校出版作品有《重構：改善 .NET 與 C# 應用程式的設計，償還欠下的技術債》、《無瑕的程式碼 軟體工匠篇：程式設計師必須做到的紀律、標準與倫理》，協助翻譯GitHub上擁有18.5K星星的《ASP.NET Core開發人員指南》，為繁體與簡體中文化的主要貢獻者。",
                //     Topic = "TBD",
                //     TopicOutline = "TBD",
                //     Room = "",
                //     Track = "",
                //     SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //     SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //     IsShow = true,
                //     Tags = new string[]{ "CM", "HackMD" },
                // },
                //new SpeakerModel {
                //    Id = "KevinYang",
                //    Name = "Kevin Yang",
                //    JobTitle = "",
                //    PictureUrl ="./img/speakers/Kevin Yang.jpg",
                //    BlogUrl = "https://blog.kevinyang.net/",
                //    FacebookUrl = "https://www.facebook.com/CKNotepad/",
                //    TwitterUrl = "",
                //    LinkedinUrl = "",
                //    Introduction = "目前擔任 Angular Taiwan、Angular Girls Taiwan 、TypeScript Taiwan 社群管理者，Angular 線上讀書會主持人。2018 年榮獲 Angular/Web GDE (Google Developer Expert) 開發專家。微軟最有價值專家 (Visual Studio and Development Technologies)。熱衷分享任何新奇的技術資訊、不務正業(跨領域)，目前已跨入的領域有會計、醫療資訊及程式開發。",
                //    Topic = "TBD",
                //    TopicOutline = "TBD",
                //    Room = "",
                //    Track = "",
                //    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //    IsShow = false,
                //    Tags = new string[]{ "CM", "HackMD" },
                //},
                // new SpeakerModel {
                //     Id = "JimmyHo",
                //     Name = "Jimmy Ho",
                //     JobTitle = "",
                //     PictureUrl ="./img/speakers/Jimmy Ho-02.jpg",
                //     BlogUrl = "https://jiaming0708.github.io/",
                //     FacebookUrl = "https://www.facebook.com/secretgogoworld",
                //     TwitterUrl = "",
                //     LinkedinUrl = "",
                //     Introduction = "我是 Jimmy ，在開發技術上從前端到後端 Dotnet，甚至 Cordova/Flutter 手機的應用也都碰，更不用說維運這方面的應用，什麼都碰什麼都學，喜歡學習、分享的一條龍工程師。",
                //     Topic = "TBD",
                //     TopicOutline = "TBD",
                //     Room = "",
                //     Track = "",
                //     SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //     SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //     IsShow = true,
                //     Tags = new string[]{ "CM", "HackMD" },
                // },
                //new SpeakerModel {
                //    Id = "GelisWu",
                //    Name = "Gelis 吳俊毅",
                //    JobTitle = "資深 .NET 技術顧問 & Microsoft MVP 連續七屆",
                //    PictureUrl ="./img/speakers/Gelis Wu.jpg",
                //    BlogUrl = "http://gelis-dotnet.blogspot.com/",
                //    FacebookUrl = "https://www.facebook.com/groups/361804473860062/",
                //    TwitterUrl = "",
                //    LinkedinUrl = "",
                //    Introduction = "我目前是個軟體生命週期導入專業顧問<br/>我專精於顧問與協助企業流程改造(電子化)協助將商業邏輯服務化、彈性化: 以 SOA 服務導向架構的方式提供 API 框架，讓各應用程式在開發時容易調用，加速開發、並可提高商業邏輯的再利用率，協助呈現介面多元化等。同時也擅長協助提升企業的軟體專案開發與工作效率，協助企業內部制定開發團隊流程 (Coding Rule/Standard) 與技術一致化，統一開發環境與技術、應用協同工作平台 Azure DevOps 建置雲端相關應用、自動化部署工具評估與導入。<br/>同時因為專案開發出身，我同時也擅長協助企業建置 ERP/CRM/CMS 或企業內部 EIP 等相關系統。",
                //    Topic = "TBD",
                //    TopicOutline = "TBD",
                //    Room = "",
                //    Track = "",
                //    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //    IsShow = false,
                //    Tags = new string[]{ "CM", "HackMD" },
                //},
                new SpeakerModel {
                    Id = "BaoChengyou",
                    Name = "鮑承佑",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/鮑承佑.jpg",
                    BlogUrl = "https://linktr.ee/windperson",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "本人於 2007 年底投身資訊業，從原本寫 Java，2009 年開始接觸 WPF、Silverlight 的 C# 桌面應用程式開始投入 .NET 開發，之後於資拓宏宇擔任軟體專案工程師，於 2014 年投入遊戲業在台灣卡普空擔任開發組組長，2018 到 2023 上半在 XR 領域相關新創擔任 CTO。<br/>Unity、Xamarin/MAUI、ASP.NET Core、Blazor、Azure SignalR 等前後端與 Azure 雲端開發技術都略懂略懂，但抓 bug比較在行。",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                   Id = "RyanChung",
                   Name = "Ryan Chung",
                   JobTitle = "Microsoft MVP",
                   PictureUrl ="./img/speakers/Ryan Chung.jpg",
                   BlogUrl = "",
                   FacebookUrl = "",
                   TwitterUrl = "",
                   LinkedinUrl = "",
                   Introduction = "Ryan Chung，行動開發學院 MobileDev.TW創辦人，曾獲微軟人工智能大賽特別獎，目前為製造業上櫃公司AI顧問、微軟MVP Summit Pre-Day / Reactor / DevDaysAsia / .NET Conf Taiwan講師、中央大學AI學程兼任講師、元智大學資工系兼任助理教授級專業技術人員。專長於雲端生成式AI應用整合開發，使用 Azure OpenAI / Azure AI / Google Gemini AI / Amazon Bedrock AI。2022年起，獲選為微軟AI MVP 人工智慧最有價值專家。",
                   Topic = "TBD",
                   TopicOutline = "TBD",
                   Room = "",
                   Track = "",
                   SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                   SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                   IsShow = false,
                   Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                    Id = "RuddyLee",
                    Name = "李智樺",
                    JobTitle = "91APP 敏捷教練",
                    PictureUrl ="./img/speakers/Ruddy Lee.jpg",
                    BlogUrl = "https://ruddyblog.wordpress.com/",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "具有超過40年的工程師經歷，擅長敏捷開發，著作有 :精實開發與看板方法、Windows Azure雲端開發、WF 工作流程引擎程式設計、微軟 VSTS 開發實戰等書。<br/>為專業的軟體開發顧問、Scrum及看板課程教學的講師。近年來；致力於推廣「開發者體驗」，專注於協助開發團隊與研發工程師的自我成長及敏捷開發實踐。曾擔任過多家資訊公司的研發部經理。現任集英信誠Mentor Trust 公司的敏捷顧問。為經常往返於二岸的精實佈道師。",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room ="",
                    Track ="",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                new SpeakerModel {
                   Id = "DemoFan",
                   Name = "Demo Fan",
                   JobTitle = "Microsoft MVP",
                   PictureUrl ="./img/speakers/DemoFan.jpg",
                   BlogUrl = "",
                   FacebookUrl = "",
                   TwitterUrl = "",
                   LinkedinUrl = "",
                   Introduction = "微軟最有價值專家（MVP）連任 18 屆，長期投入 .NET 技術推廣與 Web 開發教育，熱衷用有趣的方式講技術。目前在 SkillTree 程式教育品牌中教人寫程式，也在 twMVC 社群裡陪大家一起成長、不孤單。",
                   Topic = "TBD",
                   TopicOutline = "TBD",
                   Room = "",
                   Track = "",
                   SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                   SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                   IsShow = false,
                   Tags = new string[]{ "CM", "HackMD" },
                },
                // new SpeakerModel {
                //     Id = "Summit",
                //     Name = "孫玉峰",
                //     JobTitle = "台灣角川 數據架構師",
                //     PictureUrl ="./img/speakers/孫玉峰.jpg",
                //     BlogUrl = "",
                //     FacebookUrl = "",
                //     TwitterUrl = "",
                //     LinkedinUrl = "",
                //     Introduction = "在多個產業開發各種資料產品，包含推薦系統以及廣告數據平台，近年來的公開演講以及實務上則專注在資料工程與 MLOps 的建立，以數據驅動（Data-Driven）的觀念帶動各個產業領域的創新。<br/>曾在東吳及師大擔任業界講師，亦接受過各媒體專訪，目前也是微軟 AI 領域最有價值專家（MVP）以及 Taiwan R User Group（常態活動 MLDM Monday 主辦單位）的共同主持人。",
                //     Topic = "TBD",
                //     TopicOutline = "TBD",
                //     Room = "",
                //     Track = "",
                //     SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //     SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //     IsShow = true,
                //     Tags = new string[]{ "CM", "HackMD" },
                // },
                // new SpeakerModel {
                //    Id = "BenChen",
                //    Name = "陳奎銘",
                //    JobTitle = "Principal Data Scientist @ OneLab",
                //    PictureUrl ="./img/speakers/BenChen.jpg",
                //    BlogUrl = "",
                //    FacebookUrl = "",
                //    TwitterUrl = "",
                //    LinkedinUrl = "",
                //    Introduction = "有幸成為微軟 AI 領域 MVP 的資料科學家，致力於用資料科學解決各個領域的疑難雜症，舉凡投資、生技醫療和其他傳統產業，都有相關實務處理的經驗。除此之外，不定期也會接到授課的邀約，協助不同組織機構初探數位轉型，進入資料科學的世界。同時，我也是 R-Ladies Taipei Co-organizer，正嘗試努力每個月都舉辦活動，繼續延續社群的活力。",
                //    Topic = "TBD",
                //    TopicOutline = "TBD",
                //    Room = "",
                //    Track = "",
                //    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //    IsShow = true,
                //    Tags = new string[]{ "CM", "HackMD" },
                // },
                // new SpeakerModel {
                //    Id = "AlanTsai",
                //    Name = "Alan Tsai",
                //    JobTitle = "微軟最有價值專家",
                //    PictureUrl ="./img/speakers/Alan Tsai.jpg",
                //    BlogUrl = "https://blog.alantsai.net/",
                //    FacebookUrl = "http://fb.alantsai.net/",
                //    TwitterUrl = "http://twitter.alantsai.net/",
                //    LinkedinUrl = "http://linkedin.alantsai.net/",
                //    YouTubeUrl = "http://yt.alantsai.net/",
                //    Introduction = "熱愛學習、分享與教學，專精於 .NET (Core)、ASP.NET Core、Azure、架構設計、Container、DevOps、Bot Framework (chatbot), ==GitHub Copilot== 等領域。<br/>堅信教學是最佳的學習方式，喜歡將新知轉化為文章、影片、課程與演講，並在「Alan Tsai 的學習筆記」部落格分享。<br/>同時，也熱衷於翻譯軟體/文章，目前已翻譯了兩本書。<br/>榮幸擔任微軟最有價值專家 (MVP) - Azure和微軟認證講師 (MCT)，並擁有數十張與Azure相關的證照。<br/>除了工作之外，我也非常喜歡參與和協助社群活動，是Study4.TW的成員之一。閒暇時，我喜歡閱讀小說和打打手遊。<br/>如果有機會參加活動，歡迎找我聊聊哦！<br/>期待與大家建立聯繫，一同學習和成長！",
                //    Topic = "TBD",
                //    TopicOutline = "TBD",
                //    Room = "",
                //    Track = "",
                //    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //    IsShow = true,
                //    Tags = new string[]{ "CM", "HackMD" },
                // },
                new SpeakerModel {
                    Id = "MarcusTung",
                    Name = "Marcus Tung",
                    JobTitle = "微軟最有價值專家",
                    PictureUrl ="./img/speakers/Marcus Tung.jpg",
                    BlogUrl = "https://marcus116.blogspot.com/",
                    FacebookUrl = "https://www.facebook.com/marcustung.tech",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "現任微軟最有價值專家（Developer Technologies）和 DevOps Taiwan 技術社群志工，樂於研究與分享 後端技術，將學習與實踐的心得記錄在個人部落格 m@rcus 學習筆記上，並於粉絲團不定期分享技術開發與 Observability 相關新知。",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                // new SpeakerModel {
                //     Id = "MikeHuang",
                //     Name = "Mike Huang",
                //     JobTitle = "微軟最有價值專家",
                //     PictureUrl ="./img/speakers/Mike.jpg",
                //     BlogUrl = "https://wellwind.idv.tw/blog/",
                //     FacebookUrl = "https://www.facebook.com/fullstackledder",
                //     TwitterUrl = "",
                //     LinkedinUrl = "",
                //     Introduction = "台積電主任工程師、Angular GDE，主要熟悉 .NET WebAPI 與 Angular 開發技術，並經常於個人部落格分享學習知識。",
                //     Topic = "TBD",
                //     TopicOutline = "TBD",
                //     Room = "",
                //     Track = "",
                //     SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //     SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //     IsShow = true,
                //     Tags = new string[]{ "CM", "HackMD" },
                // },
                new SpeakerModel {
                    Id = "BillChung",
                    Name = "Bill Chung",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/Bill Chung.jpg",
                    BlogUrl = "https://www.dotblogs.com.tw/billchung",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "Microsoft MVP，熱愛寫程式與講故事",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                // new SpeakerModel {
                //     Id = "JamesTsai",
                //     Name = "James Tsai",
                //     JobTitle = "微軟最有價值專家",
                //     PictureUrl ="./img/speakers/James Tsai.jpg",
                //     BlogUrl = "",
                //     FacebookUrl = "",
                //     TwitterUrl = "",
                //     LinkedinUrl = "",
                //     Introduction = "現任 Microsoft MVP - Developer Technologies (2015~) 與 骨架資訊有限公司的技術總監。從 10 年多前開始接觸 .NET 程式開發後，經歷過撰寫各家行動平台的 App 與 Azure 雲端應用服務整合。Blog: https://xamarintech.blogspot.tw 與點部落: https://dotblogs.com.tw/jamestsai，內容涵蓋 Xamarin、Azure 服務與 Microsoft 365 的 Intune 相關應用等開發紀錄。並持續經營當前台灣最活耀的 Xamarin 社群 (Facebook 社群名稱: Xamarin Asia Developers)，與專注於跨平台應用開發與 CI/CD 整合、企業行動化資料保護…等的技術的研究與推廣。",
                //     Topic = "TBD",
                //     TopicOutline = "TBD",
                //     Room = "",
                //     Track = "",
                //     SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //     SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //     IsShow = true,
                //     Tags = new string[]{ "CM", "HackMD" },
                // },
                // new SpeakerModel {
                //     Id = "Weithenn",
                //     Name = "王偉任 Weithenn",
                //     JobTitle = "Micron - IT Staff Architect",
                //     PictureUrl ="./img/speakers/Weithenn.jpg",
                //     BlogUrl = "https://www.weithenn.org/",
                //     FacebookUrl = "",
                //     TwitterUrl = "",
                //     LinkedinUrl = "",
                //     Introduction = "連續十三年成功獲選 Microsoft MVP 和 VMware vExpert 技術專家，並長期擔任網管人雜誌技術專欄作家。<br/>曾擔任 Kubernetes Summit 2024, Hello World Dev Conoference 2024, DevOpsDays Taipei 2024、Cloud Summit 2024、SRE Conference 2024、DevOpsDays Tokyo 2024、Google DevFest Taipei 2023、.Net Conf Taiwan 2023、Modern Web Conference 2023、Kubernetes Summit 2023、DevOpsDays Taipei 2023、COSCUP 2023、Cloud Summit Taiwan 2023……等研討會講師。<br/>專長為打造 SDDC 軟體定義資料中心、HCI 超融合解決方案、IaC 基礎架構即程式碼環境……等，著有微軟 S2D 軟體定義儲存技術實戰……等共 19 本著作。",
                //     Topic = "TBD",
                //     TopicOutline = "TBD",
                //     Room = "",
                //     Track = "",
                //     SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //     SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //     IsShow = true,
                //     Tags = new string[]{ "CM", "HackMD" },
                // },
                // new SpeakerModel {
                //     Id = "JamesFu",
                //     Name = "James Fu",
                //     JobTitle = "",
                //     PictureUrl ="./img/speakers/James Fu.jpg",
                //     BlogUrl = "https://dotblogs.com.tw/jamesfu",
                //     FacebookUrl = "",
                //     TwitterUrl = "",
                //     LinkedinUrl = "",
                //     Introduction = "一位資深的資料庫專家，擁有豐富的 SQL Server 管理經驗，專精於資料庫高可用性架構、效能調校以及雲端服務整合等領域。他經營的技術部落格「五餅二魚工作室」，分享了大量實務經驗與技術文章，涵蓋從 SQL 語法優化到 Azure 雲端服務應用等多元主題。",
                //     Topic = "TBD",
                //     TopicOutline = "TBD",
                //     Room = "",
                //     Track = "",
                //     SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //     SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //     IsShow = true,
                //     Tags = new string[]{ "CM", "HackMD" },
                // },
                new SpeakerModel {
                    Id = "CaiWenlong",
                    Name = "蔡文龍",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/蔡文龍.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "連續17年微軟最有價值專家(AI + Developer 雙領域 MVP)、專業電腦圖書作家，著有超過140本以上電腦書籍，現職於僑光科技大學多媒體與遊戲設計系副教授，專長雲端應用程式、人工智慧軟體服務、遊戲設計，同時受聘各公民營企業、內訓課程開發規劃。",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room ="202 教室",
                    Track ="Azure",
                    SessionStart = new DateTime(2020, 12, 19, 10, 0, 0),
                    SessionEnd = new DateTime(2020, 12, 19, 10, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM" },
                },
                new SpeakerModel {
                    Id = "OuZhixin",
                    Name = "歐志信",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/歐志信.jpg",
                    BlogUrl = "",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "",
                    Introduction = "連續17年微軟最有價值專家、資訊圖書作者，現任職於電信業，協助政府機關與企業客戶導入生成式AI、智慧影像辨識（人臉辨識、人形辨識）應用。",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room ="202 教室",
                    Track ="Azure",
                    SessionStart = new DateTime(2020, 12, 19, 13, 10, 0),
                    SessionEnd = new DateTime(2020, 12, 19, 14, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                //new SpeakerModel {
                //    Id = "hwchiu",
                //    Name = "邱宏瑋",
                //    JobTitle = "Microsoft MVP",
                //    PictureUrl ="./img/speakers/hwchiu.png",
                //    BlogUrl = "",
                //    FacebookUrl = "",
                //    TwitterUrl = "",
                //    LinkedinUrl = "",
                //    Introduction = "目前擔任微軟 MVP (Cloud and Datacenter Management), Cloud Native Taiwan User Group 志工; 喜愛撰寫部落格分享技術，參加鐵人賽並出版 Kubernetes 相關書籍，亦有開設 Kubernetes 線上課程並經營個人 粉絲團 定期分享 Cloud Native 相關新知",
                //    Topic = "TBD",
                //    TopicOutline = "TBD",
                //    Room = "",
                //    Track = "",
                //    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //    IsShow = false,
                //    Tags = new string[]{ "CM", "HackMD" },
                //},
                //new SpeakerModel {
                //    Id = "RobersonLiou",
                //    Name = "Roberson Liou",
                //    JobTitle = "Microsoft MVP",
                //    PictureUrl ="./img/speakers/RobersonLiou.jpg",
                //    BlogUrl = "",
                //    FacebookUrl = "",
                //    TwitterUrl = "",
                //    LinkedinUrl = "",
                //    Introduction = "現任微軟最有價值專家（Developer Technologies），也是 twMVC 及 DevOps Taiwan 的社群志工。<br/>喜歡參加社群的技術交流活動，並不定期在部落格（工程良田的小球場）上記錄自己踩坑的一些心得。",
                //    Topic = "TBD",
                //    TopicOutline = "TBD",
                //    Room = "",
                //    Track = "",
                //    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //    IsShow = true,
                //    Tags = new string[]{ "CM", "HackMD" },
                //},
                //new SpeakerModel {
                //    Id = "LinZhengxiang",
                //    Name = "林正祥",
                //    JobTitle = "",
                //    PictureUrl ="./img/speakers/林正祥.jpg",
                //    BlogUrl = "",
                //    FacebookUrl = "",
                //    TwitterUrl = "",
                //    LinkedinUrl = "",
                //    Introduction = "樂於研究與分享新技術，喜歡使用各項網頁技術解決各項問題。主要專研 .NET 相關 Solution 為主，以及 Angular & Vue.js 等前端技術，並在第十二屆 iT 邦幫忙鐵人賽中的 Modern Web 組獲得佳作。於 2022 年出版 ASP.NET Core 6 實戰守則：超易懂的跨平台開發入門教學，並榮登天瓏年度排行第二名",
                //    Topic = "TBD",
                //    TopicOutline = "TBD",
                //    Room = "",
                //    Track = "",
                //    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //    IsShow = true,
                //    Tags = new string[]{ "CM", "HackMD" },
                //},
                // new SpeakerModel {
                //     Id = "EvanceKao",
                //     Name = "Evance Kao",
                //     JobTitle = "",
                //     PictureUrl ="./img/speakers/Evance Kao.jpg",
                //     BlogUrl = "",
                //     FacebookUrl = "",
                //     TwitterUrl = "",
                //     LinkedinUrl = "",
                //     Introduction = "從天氣預報斜槓到軟體開發，從每天看雲轉變為服務上雲，喜歡從不同角度看同一件事情、抽象化各種業務邏輯、製造小輪子以揣摩米其林輪胎的設計。大多鑽研 DevOps (專注在 CI/CD)、系統架構與雲端服務，實務上則有 6 年以上的雲端架構設計、開發及維護經驗，並具有公有雲助理級證照。<br/>現在專注於商品搜尋與推薦領域，嘗試以 AI 讓大家能更好的買買買。<br/>過去分享：<br/>* 更好的開發體驗 - 建造 SDK 接上 API 的腿 @ .NET Conf Taiwan 2022<br/>* 容器化你的 .NET 生產線 @ STUDY4 2023 小聚",
                //     Topic = "TBD",
                //     TopicOutline = "TBD",
                //     Room = "",
                //     Track = "",
                //     SessionStart = new DateTime(2022, 12, 17, 0, 0, 0),
                //     SessionEnd = new DateTime(2022, 12, 17, 0, 0, 0),
                //     IsShow = true,
                //     Tags = new string[]{ "CM", "HackMD" },
                // },
                new SpeakerModel {
                    Id = "JimmyLiao",
                    Name = "Jimmy Liao",
                    JobTitle = "",
                    PictureUrl ="./img/speakers/JimmyLiao.jpg",
                    BlogUrl = "https://jimmyliao.net/",
                    FacebookUrl = "",
                    TwitterUrl = "",
                    LinkedinUrl = "https://www.linkedin.com/in/jimmyliao/",
                    Introduction = "Jimmy Liao 先後就職於 Appier/Microsoft/InfuseAI/IBM 。專業技能橫跨應用程式、手機應用、後端開發、廣告投放、機器學習專案開發，近期致力於 Generative AI 以及相關應用推廣，協助客戶技術落實及技術諮詢。目前為 Google 社群開發專家 (AI GDE) 與微軟社群開發專家 (AI MVP) 。<br/>日常生活就是跑步，曾經以跑步為通勤工具之一 (單程 20+ km)。<br/>As the Google AI GDE and Microsoft AI MVP and with 20+ years experience as technical lead in large enterprise and startup. Jimmy Liao act as GenAI Solution Architect now. He focus on solution architecture design, PoC, Production with modern solutions. Also for Generative AI/AI Application landing, education, and communities.",
                    Topic = "TBD",
                    TopicOutline = "TBD",
                    Room = "",
                    Track = "",
                    SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                    SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                    IsShow = true,
                    Tags = new string[]{ "CM", "HackMD" },
                },
                // new SpeakerModel {
                //     Id = "Chuck",
                //     Name = "陳復楷",
                //     JobTitle = "",
                //     PictureUrl ="./img/speakers/Chuck.jpg",
                //     BlogUrl = "",
                //     FacebookUrl = "",
                //     TwitterUrl = "",
                //     LinkedinUrl = "",
                //     Introduction = "台積電資深工程師，穿梭於各大社群，熱情的南部鄉親",
                //     Topic = "TBD",
                //     TopicOutline = "TBD",

                //     Room = "",
                //     Track = "",
                //     SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //     SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //     IsShow = true,
                //     Tags = new string[]{ "CM", "HackMD" },
                // },
                // new SpeakerModel {
                //     Id = "ChrisLiu",
                //     Name = "Chris Liu",
                //     JobTitle = "",
                //     PictureUrl ="./img/speakers/Chris Liu.jpg",
                //     BlogUrl = "",
                //     FacebookUrl = "",
                //     TwitterUrl = "",
                //     LinkedinUrl = "",
                //     Introduction = "前某義大利餐廳行政主廚，曾於兩間台灣金流界龍頭任職，也曾擔任過某電子支付公司研發部主管，現為 Geek & Nerd Studios CEO 喜歡協助客戶完成技術導入，對他而言程式就跟料理一樣 keep learning, keep your knife sharpen。",
                //     Topic = "TBD",
                //     TopicOutline = "TBD",
                //     Room = "",
                //     Track = "",
                //     SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //     SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //     IsShow = true,
                //     Tags = new string[]{ "CM", "HackMD" },
                // },
                // new SpeakerModel {
                //     Id = "KeiLiao",
                //     Name = "Kei Liao",
                //     JobTitle = "",
                //     PictureUrl ="./img/speakers/KeiLiao.jpg",
                //     BlogUrl = "",
                //     FacebookUrl = "",
                //     TwitterUrl = "",
                //     LinkedinUrl = "",
                //     Introduction = "從 Android 及 iOS 轉往 C# .NET 後端的資深工程師，持續在工程師的道路上精進自己。",
                //     Topic = "TBD",
                //     TopicOutline = "TBD",
                //     Room = "",
                //     Track = "",
                //     SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //     SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //     IsShow = true,
                //     Tags = new string[]{ "CM", "HackMD" },
                // },
                // new SpeakerModel {
                //     Id = "WangQuanfu",
                //     Name = "王泉富",
                //     JobTitle = "",
                //     PictureUrl ="./img/speakers/王泉富.jpg",
                //     BlogUrl = "",
                //     FacebookUrl = "",
                //     TwitterUrl = "",
                //     LinkedinUrl = "",
                //     Introduction = "一個喜歡從零開始學習的工程師",
                //     Topic = "TBD",
                //     TopicOutline = "TBD",
                //     Room = "",
                //     Track = "",
                //     SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //     SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //     IsShow = true,
                //     Tags = new string[]{ "CM", "HackMD" },
                // },
                // new SpeakerModel {
                //     Id = "ArthurChang",
                //     Name = "Arthur Chang",
                //     JobTitle = "",
                //     PictureUrl ="./img/speakers/Arthur Chang.jpg",
                //     BlogUrl = "",
                //     FacebookUrl = "",
                //     TwitterUrl = "",
                //     LinkedinUrl = "",
                //     Introduction = "專注領域驅動設計與軟體架構，多年實戰經驗，涵蓋敏捷開發、微服務、架構演進等。擅長結合業務需求與技術實現，提供實用解決方案。",
                //     Topic = "TBD",
                //     TopicOutline = "TBD",
                //     Room = "",
                //     Track = "",
                //     SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //     SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //     IsShow = true,
                //     Tags = new string[]{ "CM", "HackMD" },
                // },
                // new SpeakerModel {
                //     Id = "JrtingShiau",
                //     Name = "蕭晊莛",
                //     JobTitle = "Technical Manager",
                //     PictureUrl ="./img/speakers/Jrting Shiau.jpg",
                //     BlogUrl = "",
                //     FacebookUrl = "",
                //     TwitterUrl = "",
                //     LinkedinUrl = "",
                //     Introduction = "目前任職於新加坡商鈦坦科技，擔任 Technical Manager",
                //     Topic = "TBD",
                //     TopicOutline = "TBD",
                //     Room = "",
                //     Track = "",
                //     SessionStart = new DateTime(2025, 11, 29, 0, 0, 0),
                //     SessionEnd = new DateTime(2025, 11, 29, 0, 0, 0),
                //     IsShow = true,
                //     Tags = new string[]{ "CM", "HackMD" },
                // }
            };

            return speakers;
        }
    }
}
